

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const  FETCH_REQUEST_FAILURE = 'FETCH_REQUEST_FAILURE';


export const FETCH_YACHTS_REQUEST = 'FETCH_YACHTS_REQUEST';
export const FETCH_YACHTS_SUCCESS = 'FETCH_YACHTS_SUCCESS';
export const FETCH_YACHTS_FAILURE = 'FETCH_YACHTS_FAILURE';
export const ADD_YACHT = 'ADD_YACHT';
export const UPDATE_YACHT = 'UPDATE_YACHT';
export const DELETE_YACHT = 'DELETE_YACHT';

export const FETCH_OWNER_YACHTS_SUCCESS = 'FETCH_OWNER_YACHTS_SUCCESS';
export const FETCH_SINGLE_YACHT_SUCCESS = 'FETCH_SINGLE_YACHT_SUCCESS';
export const FETCH_YACHTOWNERS_SUCCESS = 'FETCH_YACHTOWNERS_SUCCESS';
export const FETCH_SINGLE_YACHTOWNER_SUCCESS = 'FETCH_SINGLE_YACHTOWNER_SUCCESS';

export const FETCH_OWNER_PAYOUTS_SUCCESS = 'FETCH_OWNER_PAYOUTS_SUCCESS';


//auth 
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_ERROR_RESET = 'AUTH_ERROR_RESET';


export const ADD_BLOCK_REQUEST = "ADD_BLOCK_REQUEST";
export const ADD_BLOCK_SUCCESS = "ADD_BLOCK_SUCCESS";
export const ADD_BLOCK_FAILURE = "ADD_BLOCK_FAILURE";

export const FETCH_BLOCKS_REQUEST = "FETCH_BLOCKS_REQUEST";
export const FETCH_BLOCKS_SUCCESS = "FETCH_BLOCKS_SUCCESS";
export const FETCH_BLOCKS_FAILURE = "FETCH_BLOCKS_FAILURE";

export const UPDATE_BLOCK_REQUEST = "UPDATE_BLOCK_REQUEST";
export const UPDATE_BLOCK_SUCCESS = "UPDATE_BLOCK_SUCCESS";
export const UPDATE_BLOCK_FAILURE = "UPDATE_BLOCK_FAILURE";

export const DELETE_BLOCK_REQUEST = "DELETE_BLOCK_REQUEST";
export const DELETE_BLOCK_SUCCESS = "DELETE_BLOCK_SUCCESS";
export const DELETE_BLOCK_FAILURE = "DELETE_BLOCK_FAILURE";
